### ISSUE TITLE
An available audio input isn't appearing in the dropdown list

### ISSUE THREAD

**Issue by barryburd** [fredemmott/StreamDeck-AudioSwitcher#108] opened 2023-05-14 18:25 UTC
### Discussed in https://github.com/fredemmott/StreamDeck-AudioSwitcher/discussions/107

<div type='discussions-op-text'>

<sup>Originally posted by **barryburd** May 14, 2023</sup>
I have a Xenyx 302 microphone that appears in my list of Zoom devices as USB Audio CODEC. The same name appears in my macOS (Ventura) list of available input devices. But USB Audio CODEC isn't one of the options in the "Set Audio Device" button's dropdown list. When I unplug the device or plug in the device, the dropdown list doesn't change. So I assume that the Audio Switcher plugin isn't sensing this device. What can I do about this?</div>

**Comment by fredemmott** [comment] 2023-05-14 18:26
Closing as duplicate of discussion

**Closed by fredemmott** 2023-05-14 18:26 UTC
