### ISSUE TITLE
[MacOS 13.0.1] Toggling Audio changes 'Alert Source' (with video)

### ISSUE THREAD

**Issue by jwmann** [fredemmott/StreamDeck-AudioSwitcher#96] opened 2022-12-08 19:28 UTC
**Describe the bug**
When toggling audio, I expect only the output source to change but the Alert source also changes

https://user-images.githubusercontent.com/436270/206546932-4dbef672-b663-4576-b70c-b4b3781152a9.mp4

**To Reproduce**
1. Toggle Audio
2. 'Play sound effects trhough' source changes
 
**Expected behavior**
Only the Output to switch.

**Debugging Information**

[Video](https://jwm.d.pr/v/qU5yqf/zYC9B4tiGg)

**Log File**
Looked at the logs but didn't see any lines relating to this plugin. Only other plugins.

** Operating System **

MacOS 13.0.1

**Comment by fredemmott** [comment] 2022-12-08 19:36
This seems to be the same as https://github.com/fredemmott/StreamDeck-AudioSwitcher/issues/66 - it’s closed as it appears to be a macOS bug, and is reproducible without a stream deck using built in macOS tools. The plugin doesn’t ask to do this, and can’t prevent it.

**Closed by fredemmott** 2022-12-08 19:36 UTC
