### ISSUE TITLE
MAC: problem with Sound Effects

### ISSUE THREAD

**Issue by joco-sp** [fredemmott/StreamDeck-AudioSwitcher#66] opened 2021-12-09 14:36 UTC
### Discussed in https://github.com/fredemmott/StreamDeck-AudioSwitcher/discussions/65

<div type='discussions-op-text'>

<sup>Originally posted by **joco-sp** December  9, 2021</sup>
The plugin works great. Tnx for it.
 
But I see one issue, which is quite annoying. When you change the Audio device, it also changes the "Sound Effects" setting "Play sound effects through". The problem is that it doesn't switch it again.
My default setting is set to "Selected sound output device".

My suggestions are:
- Leave it to "Selected sound output device"
- change it always to "Selected sound output device"
- change it also when you change the "Output"
- don't do anything with.

I'm using MacOS v 11.6. 
Plugin version 3.0</div>

**Comment by schoenwaldnils** [comment] 2022-02-01 15:56
Same problem here. In my opinion it should not touch the sound effect settings 🤔

**Comment by fredemmott** [comment] 2022-07-16 23:37
Closing: I'm unable to reproduce this; I've not changed the implementation, however it is only affecting the output device for me, not the 'sounds effect' one, and that is what the plugin has always asked MacOS to do.

Perhaps it was fixed by Apple in an update? I'm running 12.4

**Closed by fredemmott** 2022-07-16 23:37 UTC
Labels: mac

**Comment by joco-sp** [comment] 2022-08-01 09:57
https://user-images.githubusercontent.com/51315716/182123574-e87b7d6c-f7ec-477d-8607-f35adbd1d75c.mov

I updated my MAC OS, Stream deck and also uninstalled and installed back the plugin, but I have the same problem. I attached the video of the issue. Hope it helps.

**Comment by fredemmott** [comment] 2022-10-11 15:54
I can't reproduce this at all, also on an M1 with Montery 12.6 - however, what I can *sometimes* reproduce is:

1. quit the streamdeck software entirely
2. set sound effects to 'use the system device'
3. switch to the output tab in sound settings
4. change the device
5. change back to the effects tab, see it's changed
6. go back to the output tab
7. change the device
8. go back, see it's still stuck on the previous device rather than following

The separation/coupling of effects and output simply seems buggy in MacOS, regardless of if you're using the plugin or not, and the plugin explicitly requests to only change the output. There doesn't seem to be anything to change or realistically investigate in the plugin.

**Comment by schoenwaldnils** [comment] 2022-10-11 16:11
Hm .. in macOS I can't reproduce what you are describing.

[My Test Video.mp4](https://i.schoen.world/4kbLs.mp4)

![Screen-Shot-2022-10-11-18-07-43 69](https://user-images.githubusercontent.com/2837064/195143647-87f43c35-6d40-49bc-ad0c-6e4bb0c35441.png)

It seems the current device is set on the 'Sound Effects' panel before switching to the new device 🤔
Sadly this is currently rendering this plugin useless for me because I need to hear the notifications :/

**Comment by fredemmott** [comment] 2022-10-11 16:13
> In macOS I can't reproduce what you are describing.

Sometimes I can reproduce that 5 times in a row, sometimes 5 attempts and it doesn't happen; it's just flakey.

Unfortunately, evidence that things are acting differently doesn't help diagnose: I need a way to consistently *make* things act differently.

**Comment by schoenwaldnils** [comment] 2022-10-11 16:18
I checked in the Midi Setup. It seems the selected output device is set before updating the output device 🤔 
As if macOS doesn't want the sounds output to be changed from external (the plugin)

> Unfortunately, evidence that things are acting differently doesn't help diagnose: I need a way to consistently make things act differently.

True :/

**Comment by joco-sp** [comment] 2023-08-08 06:37
> Just FYI checked it again and sadly on macOS Ventura 13.4.1 still the same issue. When pressing the button the sound effects output is set to the current output device, then the output device is switched.
> 
> This issue seems related: [deweller/switchaudio-osx#12](https://github.com/deweller/switchaudio-osx/issues/12)
> 
> New Video [clip.mp4](https://i.schoen.world/fI3RC.mp4)

I have the same issue.

Can't you add another line to the code, so that when you change the Oruput device, you set the Sound Effects as the "Selected sound output device"?
