### ISSUE TITLE
Plugin broken after windows update

### ISSUE THREAD

**Issue by Zaguaiio** [fredemmott/StreamDeck-AudioSwitcher#37] opened 2021-03-27 20:16 UTC
**Describe the bug**
Have been using audio switch for couple of year now without any issue but after the last windows update seems to be broken. No error or no warning is given by delgato screen deck icon. It actually shows like the device is changing but is not really changed at the windows level:

**To Reproduce**
1. Assign you two devices
2. Click on elgato icon in your stream deck
3. Action is acknowledged by the plugin based on the icon
4. Device is not changed at windows level

**Expected behavior**
Windows device should be changed when pressing the button

**Debugging Information**

- screenshot of the expanded Debug Information section of property inspector

Before pressing button
![image](https://user-images.githubusercontent.com/4677018/112733647-cbff1600-8f06-11eb-9041-737d6c1461d3.png)

After pressing button
![image](https://user-images.githubusercontent.com/4677018/112733655-da4d3200-8f06-11eb-8ef3-c78828528db4.png)

- how recent is "Last State Change" in that section? - is it seconds, minutes, or hours?
- how frequently the 'last state change' is changing, if at all?

**Log File**
Attached
[com.fredemmott.audiooutputswitch0.log](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/6216343/com.fredemmott.audiooutputswitch0.log)

** Operating System **

Edition	Windows 10 Pro
Version	20H2
Installed on	‎3/‎26/‎2021
OS build	19042.867
Experience	Windows Feature Experience Pack 120.2212.551.0

**Additional context**

**Comment by ACleverImposter** [comment] 2021-05-17 17:44
+1
I have the same issue and I can replicate as described here.

**Comment by Zaguaiio** [comment] 2021-05-18 01:32
Hi @ACleverImposter 

After a couple of reboots I noticed the plugin was using old Device entries (For example: I had 2 different entries for the same headset device) After the selecting the other one the plugin started working again

I asume that part of the windows update regenerated the Audio Devices entries and the older ones were not working. Let me know if this works for you and we can document it and close this ticket.

**Comment by ACleverImposter** [comment] 2021-05-20 19:09
Hi @Zaguaiio 
Thanks for the detail.  That is indeed the case for me as well.  I uninstalled and reinstalled the plugin and see the multiple entries clearly now.

I don't see that this clears the bug though.  While it is a work around its still not identifiable in the Audio Switcher selector.  I don't have multiple devices that show up in my Devices Manager or other Audio options within Windows or even meeting/conferencing so there is a way to differentiate a ghost from the real assume that for some reason windows is actually reporting multiple devices in real-time.  

I suspect that the audio switcher is caching this somewhere???  I don't have insight into this but considering that other audio apps are continuing to behave as expected seems more likely.

**Comment by fredemmott** [comment] 2021-06-24 16:53
Closing as duplicate of #36

**Closed by fredemmott** 2021-06-24 16:53 UTC

**Comment by fredemmott** [comment] 2021-06-24 16:57
Windows does report old device IDs, and on MacOS the plugin caches them. Most audio apps ignore devices that are reported as installed-but-not-present, but this plugin can't when it's configured to use a specific device, as the configuration should stay (and be readable in the properties) even if it's a USB device that's temporarily unplugged/turned off.
