### ISSUE TITLE
Plugin stopped working and options are not displayed

### ISSUE THREAD

**Issue by Raiden38** [fredemmott/StreamDeck-AudioSwitcher#104] opened 2023-01-03 01:17 UTC
**Describe the bug**
Sudenly, the plugin stopped working. When I press on the stremdeck icon, I have a yellow exclamation mark. In the streamdeck app, when I go to check the settings, nothing appears (see screenshot)

**To Reproduce**
No Idea, it just happened at some time.
I tried removing the installing back the plugin, it worked a few times and stop working.

**Debugging Information**

- screenshot of the expanded Debug Information section of property inspector
- how recent is "Last State Change" in that section? - is it seconds, minutes, or hours?
- how frequently the 'last state change' is changing, if at all?

**Log File**
Included log file and photo

** Operating System **
Win10
![Capture](https://user-images.githubusercontent.com/6731214/210289107-4fb2e7c9-ef45-43c8-b95d-643195eec5d1.PNG)
[StreamDeck0.log](https://github.com/fredemmott/StreamDeck-AudioSwitcher/files/10333926/StreamDeck0.log)

**Comment by fredemmott** [comment] 2023-01-04 00:47
Do you have any related .dmp files in %LOCALAPPDATA%\CrashDumps?

**Comment by Raiden38** [comment] 2023-01-09 02:08
Hi Fredemmott,

There is nothing related to the plugin in that folder..

**Comment by fredemmott** [comment] 2023-01-09 03:06
Can you try [this build](https://github.com/fredemmott/StreamDeck-AudioSwitcher/suites/10251788641/artifacts/502927667) ?

**Comment by Raiden38** [comment] 2023-01-09 03:14
Just installed it, will let you know if it works. Thanks!

**Comment by fredemmott** [comment] 2023-01-10 00:00
Can you open regedit, and in `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\sdaudioswitch.exe` create these two values:

- "DumpCount" - DWORD - 3
- "DumpType" - DWORD - 2

... then restart the streamdeck software.

You will then hopefully have a dump in `%LOCALAPPDATA%\CrashDumps`

**Comment by Raiden38** [comment] 2023-01-10 00:09
Strangly, the sdaudioswitch.exe folder was not created. I created it and added the 2 values. When I started back streamdeck, the plugin was working correctly. Will let it run to see if it crashes at some point. Thanks!

**Comment by Raiden38** [comment] 2023-01-11 03:36
Hi! So today, it stopped working. and I still have nothing in CrashDumps... 
![Capture](https://user-images.githubusercontent.com/6731214/211711911-8d88f336-06c7-4a21-b49e-23fb88af5236.PNG)
![2](https://user-images.githubusercontent.com/6731214/211711981-c3dafda4-c757-4a2e-9996-47bc5f6dcff7.PNG)

**Comment by tinue** [comment] 2023-01-25 06:01
Hello, same thing on a Mac. It appears to be related to a Stream Deck software update that happened a while ago.

**Comment by Raiden38** [comment] 2023-02-05 00:42
Not sure why but everything seems to be working fine since a few days, with the built by @fredemmott above... Not sure if it's resolved or just luck :)

**Comment by YaPlusDePile** [comment] 2023-03-05 22:43
Hello, i got the same issue, and nothing in %LOCALAPPDATA%\CrashDumps.

![image](https://user-images.githubusercontent.com/56695668/222989920-a3b8d3a4-0121-4349-bb0c-f1b009cbdcb4.png)

I have tried to install the build in this post:

> Can you try [this build](https://github.com/fredemmott/StreamDeck-AudioSwitcher/suites/10251788641/artifacts/502927667) ?

and it works now.
the issue seem to come after an StreamDeck software upgrade.

if i can give you some things to find source of the problem don't hesitate to ask me.
Thanks to @fredemmott  for the build 😉

**Comment by Jinks5710** [comment] 2023-03-18 08:52
Hi, I just encountered the same issue after a recent stream deck update. I have tried replicating the steps above with no success, same issue as the others. The plugin has stopped working and options to change audio sources are not displayed.

**Comment by StickleTH** [comment] 2023-06-10 15:49
Been having the same issue as well. I tried making the new directory in regedit as well since it did not exist, but still does not output a file. It doesn't seem like it is fully crashing, which might be why it isn't outputting anything. 

Previously, I had to uninstall the plugin and reinstall every time as restarting the StreamDeck app was not sufficient even running as admin. But now, closing the app and opening again (normal permissions) is enough to fix it. Device matching is set to Fuzzy, but doesn't seem like it matters as none of the properties are loading. Always breaks with windows restarting.

If there's any other way to get info you might need, let us know

**Comment by Alaknar** [comment] 2023-07-19 12:28
+1, same issue here. 

Workaround*:

I just restarted my Stream Deck software (right click on the Tray icon -> Quit -> relaunch the software) and the button works again.

* well, this is what I did right now, can't verify if this is an actual workaround that can be reproduced every time

**Comment by fredemmott** [comment] 2023-12-31 17:59
Can anyone still encountering this problem give the version at https://nightly.link/fredemmott/StreamDeck-AudioSwitcher/actions/runs/7371931988/com.fredemmott.audiooutputswitch.streamDeckPlugin.zip a try and let me know how it goes?

**Comment by sulzer** [comment] 2024-02-01 11:44
> Can anyone still encountering this problem give the version at https://nightly.link/fredemmott/StreamDeck-AudioSwitcher/actions/runs/7371931988/com.fredemmott.audiooutputswitch.streamDeckPlugin.zip a try and let me know how it goes?

I've just tried this version and it works perfectly.  Thank you!

**Closed** 2024-02-01 21:42 UTC
Labels: question
