### ISSUE TITLE
Switch both output device type at the same time

### ISSUE THREAD

**Issue by tommysanterre** [fredemmott/StreamDeck-AudioSwitcher#61] opened 2021-11-30 21:55 UTC
**Is your feature request related to a problem? Please describe.**
When switching between 2 headset I need to change both the main output device and the communication output device.

**Describe the solution you'd like**
I'd like an option to switch both at the same time.

**Describe alternatives you've considered**
I created an action for both output and press each one in succession

**Additional context**

**Comment by fredemmott** [comment] 2021-11-30 22:25
Duplicate of #2

I won't be implementing this as this plugin attempts to indicate the current state, and there isn't an intuitive (and correct) behavior if they get out of sync.

A better workaround is to use a Multi-action switch (see release notes at https://www.reddit.com/r/ElgatoGaming/comments/dvdg6b/stream_deck_update_44_multi_action_switch_random/ ) - then you have one button that toggles between two multi actions

**Closed by fredemmott** 2021-11-30 22:25 UTC
