### ISSUE TITLE
Keeps crashing and disconnecting USB devices 

### ISSUE THREAD

**Issue by neomagic75** [fredemmott/StreamDeck-AudioSwitcher#109] opened 2023-05-29 18:50 UTC
The Plugin keeps crashing and disconnecting all(!) of my USB devices several times a day. They will all cease to function and be lit for a few seconds, then come back "online". Reinstall did not help.

Windows Event viewer says:

Faulting application name: sdaudioswitch.exe, version: 3.1.3.66, time stamp: 0x6325ffd0
Faulting module name: sdaudioswitch.exe, version: 3.1.3.66, time stamp: 0x6325ffd0
Exception code: 0xc0000005
Fault offset: 0x000000000002b134
Faulting process id: 0x0x4354
Faulting application start time: 0x0x1D9923E41D680F6
Faulting application path: C:\Users\xxx\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.audiooutputswitch.sdPlugin\sdaudioswitch.exe
Faulting module path: C:\Users\xxx\AppData\Roaming\Elgato\StreamDeck\Plugins\com.fredemmott.audiooutputswitch.sdPlugin\sdaudioswitch.exe
Report Id: dd694ca4-3837-4ef3-b1e7-b1f1d90270d0
Faulting package full name: 
Faulting package-relative application ID:

**Comment by fredemmott** [comment] 2023-05-29 18:52
This plugin is not capable of disconnecting your devices unless the drivers are extremely buggy, in which case there’s nothing the plugin can do to prevent it; it is likely that your devices disconnecting crashes the plugin.

**Comment by fredemmott** [comment] 2023-05-29 18:53
Closing as a duplicate of other crash issues; see information on them for information on how to get a dump. Without them I’m unable to look into this.

**Closed by fredemmott** 2023-05-29 18:53 UTC

**Comment by neomagic75** [comment] 2023-05-29 19:03
Thanks for the swift reply.

That would be:

- Stream Deck XL
- Stream Deck +
- Razer Naga Pro
- Razer Tartarus
- Razer Black Widow Keyboard
- OME external sound card

all going offline at the same time.

I uninstalled the plugin an will report back in a few days.

**Comment by neomagic75** [comment] 2023-06-01 22:55
You were right, uninstalling the plugin did not stop the crashes from ocurring.

Thanks for the help!
