### ISSUE TITLE
Mac Only: duplicate devices

### ISSUE THREAD

**Issue by zpriddy** [fredemmott/StreamDeck-AudioSwitcher#56] opened 2021-10-12 18:44 UTC
**Describe the bug**
Every time i reboot my machine I have to re-configure the buttons to select the audio device. When i go to update it, it will show 2 of the same audio interfaces, one is the selected one (that doesnt work anymore after reboot) and the other is the 'newly detected' audio interface with the same name. This also happens if the audio interface is unplugged at any point in time.

**To Reproduce**
1. Make a button to select a USB connected audio interface
2. Reboot machine
3. Try to use button
4. Re-configure

**Expected behavior**

I am assuming that the device path changes on reboot, however if there is only one device with the same name connected, is it possible to also use the device name as a reference.. This would allow the config to stay static between reboots.

**Debugging Information**

- Mac OS 11.6
- Newest installed version from the store

**Comment by tadaszelvys** [comment] 2021-11-03 12:53
Same problem with windows 11. I have external sound card and dell u4320q monitor with speakers, after reboot - external sound card is ok, but dell monitor is marked as unplugged and new line with same monitor is added and I have to select this new item after every reboo
![Screenshot 2021-11-03 145320](https://user-images.githubusercontent.com/247136/140063444-6575a2c0-dd04-405e-a05a-60ce9126d858.png)
t.

**Comment by mattdelcampo** [comment] 2021-11-04 22:49
I have the same issue on Windows 11 except I can't even see the settings or change them until I completely uninstall the plug and reinstall. Simply removing/readding the button or rebooting the physical device or rebooting the software does not bring the settings back - only reinstalling the plugin entirely.
![screenshot](https://user-images.githubusercontent.com/9485647/140430967-8b8ef239-3805-4ecf-94bf-450807cb099c.png)

**Comment by JacobRReed** [comment] 2021-11-23 13:48
Can confirm, same issue. Any update on this @fredemmott

**Comment by shapman88** [comment] 2021-12-20 02:02
I'm having the same issue after updating the stream deck application to version 5.1.4.14753. I'm not even seeing the option to reconfigure the devices.

**Comment by SauceyGit** [comment] 2022-01-05 17:57
> StreamDeck v.5.1.4.14753
> Audio Switcher v.3.0 (2/16/2021)
> Microsoft Windows 11 Home Version.10.0.22000 Build 22000

[While this](https://github.com/fredemmott/StreamDeck-AudioSwitcher/issues/58#issuecomment-956429356) does resolve the issue temporarily, finding this thread explains why it's not a permanent fix. 

Are the device IDs getting remapped on a reboot? Would having multiple accounts on a single device also play a part (there are two active MSAs on this PC)?

![image](https://user-images.githubusercontent.com/97188197/148265480-4f170c84-eb11-4b73-8a8b-0e1aca247350.png)

**Comment by ptahbe** [comment] 2022-02-09 19:02
I have the same issue. After reboot Set Audio Device does not work anymore. Re-configure doesn't work either. I have to delete it and set it again.

StreamDeck 5.2.0.14948
Audio Switcher 3.0
Windows 11 Pro 21H2 (22000.469)

**Comment by fredemmott** [comment] 2022-02-11 13:47
Windows: #74

Mac (original report here): unknown cause

**Comment by wyne** [comment] 2022-03-10 05:31
I'm having the same issue. I have no idea how to fix the actual issue, so I did the next best thing which was to over-engineer a workaround. Here's my workaround: https://github.com/wyne/StreamDeck-AudioSwitcher-workaround/blob/main/README.md

What it does:
- Create a launch agent that detects USB device changes (you specific a specific one to listen to)
- If it detects a new id, kill stream deck, overwrite with the new value, then relaunch streamdeck.

**Comment by fredemmott** [comment] 2022-03-10 05:40
Closing this: this is either #73 or #74 - it seems likely that the comments on this issue are a mix of both.

As for a real fix: https://github.com/fredemmott/AudioDeviceLib/commit/ba598db5e9364846bb9ebeb8144b06d7ffc626b5 is the start of it. Also needs to work on mac.

The issues:

- #73, windows and macos: bug in the plugins (via audiodevicelib): these plugins don't work well if the device doesn't exist the entire time the streamdeck software is running.
- #74: windows only: bug in several audio device drivers: Microsoft requires "the endpoint ID string remains unchanged across system restarts, and the endpoint ID string of a USB audio device remains unchanged if the user unplugs the device and plugs it back in.". This is not the case for several popular drivers. This is windows-specific as macos does not have an equivalent ID, so everything is fuzzy based on the name.

Real fixes:
- #73: handle device plug/unplug events
- #74: provide an *option* to use fuzzy matching on windows. This is required for things to work for people with buggy drivers, but a regression for people with good drivers.

**Comment by fredemmott** [comment] 2022-03-10 05:45
@wyne: hopefully that's useful, and I appreciate your workaround.

There's a few reasons that I've not addressed these issues:
* I do not own hardware that has these buggy drivers; this makes it hard and time consuming to dig into
* I generally don't have hot-pluggable audio devices handy, and for whatever reason, my audio devices reliably fully initialize before the streamdeck software; again, this makes this time consuming to dig into
* It's a hobby project - I work on it as form of recreation, when it will act as such. I don't work for Elgato/Corsair - though, for disclosure, I did previously get a 1 year free license for StreamDeck mobile from them.

**Comment by fredemmott** [comment] 2022-03-10 05:47
It's also reasonably likely that this plugin needs a change similar to https://github.com/fredemmott/StreamDeck-AudioMute/commit/4b3f7a37769110b1c92a278f5834ab16c898c0d3

**Comment by fredemmott** [comment] 2022-03-10 05:55
Sorry - actually reopening: most of the comments here are #73 or #74, but @wyne and OP are having the same symptoms as #74, but on MacOS, and the cause of #74 is windows-specific

It would be very useful if those of you having duplicate devices on MacOS could grab the 'demos' from https://github.com/fredemmott/AudioDeviceLib/releases , extract them, and run './list-devices' from a terminal, both before and after rebooting, and post the output of both runs here.

**Comment by wyne** [comment] 2022-03-10 07:17
I just restarted and the device path has not changed. However, when I did this previously using https://github.com/deweller/switchaudio-osx  instead of your `list-devices`, the number at the end of the ID is what changed.

Example output from `list-devices`:
```
"Vanatoo T0"
	ID:        "output/AppleUSBAudioEngine:Vanatoo:Vanatoo T0:2200000:1"
	Interface: "Vanatoo T0"
	Endpoint:  ""
	State:     CONNECTED
```

The `T0:2200000:1` would change to something like `T0:3200000:1` in my previous debugging.

**Comment by fredemmott** [comment] 2022-03-10 14:53
Thanks - so this is *very* similar to #74, except that unlike on windows, there isn't an explicit guarantee that this identifier is stable, so isn't a buggy driver

It seems likely the fix is the same: add an option just to match the name, not ID

**Comment by fredemmott** [comment] 2022-07-17 00:17
> This also happens if the audio interface is unplugged at any point in time.

This is fixed for the next version if it's plugged into the same port

**Closed** 2022-07-17 03:10 UTC
Labels: mac

**Comment by fredemmott** [comment] 2022-07-17 14:39
> there isn't an explicit guarantee that this identifier is stable

Turns out I was wrong here: this *is* meant to be stable, however:
* on multi-cpu (not multi-core) machines it may vary. This doesn't seem to be a practical concern
* if you have a USB sound card and plug it into a different port, the ID varies

Regardless, the fuzzy matching added in https://github.com/fredemmott/StreamDeck-AudioSwitcher/releases/tag/v3.1-beta2 should resolve this
